# Generated by Django 6.0.3 on 2026-04-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Our_First_App', '0003_customuser_course_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=10),
        ),
    ]
