# Generated by Django 6.0.3 on 2026-04-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Our_First_App', '0004_weeklylog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='submission_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
