# Generated by Django 6.0.3 on 2026-04-28 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Our_First_App', '0005_weeklylog_submission_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='Our_First_App.weeklylog')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
