# Generated by Django 6.0.3 on 2026-05-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Our_First_App', '0007_supervisorreview_previous_status_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
